language: c

compiler:
  - gcc

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gperf
  - sudo apt-get install -qq lua5.1 liblua5.1-0-dev
  - sudo apt-get install -qq libtokyocabinet-dev
  - autoreconf -vfi

script:
  - ./configure || { cat config.log; false; }
  - make clean all check || { cat test/test-suite.log; /bin/false }
  - make distcheck

## whitelist
branches:
  only:
    - master
    - next

notifications:
  email:
    - devel@fresse.org
