language: c

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gengetopt
  - sudo apt-get install -qq help2man
  - sudo apt-get install -qq texinfo
  - sudo apt-get install -qq texlive
  - sudo apt-get install -qq lua5.1 liblua5.1-0-dev
  - sudo apt-get install -qq libev-dev
  - sudo apt-get install -qq bison
  - sudo apt-get install -qq flex
  - sudo apt-get install -qq gperf
  - sudo apt-get install -qq libtokyocabinet-dev
  - autoreconf -vfi

script:
  - ./configure --enable-server || (cat config.log && /bin/false)
  - make clean all check distcheck || (cat test/test-suite.log && /bin/false)

## whitelist
branches:
  only:
    - master
    - next

notifications:
  email:
    - devel@fresse.org
