language: c

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get install -qq gengetopt
  - sudo apt-get install -qq help2man
  - sudo apt-get install -qq texinfo
  - sudo apt-get install -qq texlive
  - sudo apt-get install -qq lua
  - sudo apt-get install -qq libev
  - autoreconf -vfi

script: ./configure && make clean all check distcheck || (cat test/test-suite.log && /bin/false)

## whitelist
branches:
  only:
    - master
    - next

notifications:
  email:
    - devel@fresse.org
